return {
  enabled = true,
  -- Binary / non-text files we never want in pickers (images, PDFs,
  -- office docs, archives, media, fonts, ...).
  exclude = {
    '*.png',
    '*.jpg',
    '*.jpeg',
    '*.gif',
    '*.bmp',
    '*.tiff',
    '*.ico',
    '*.webp',
    '*.avif',
    '*.heic',
    '*.psd',
    '*.ai',
    '*.eps',
    '*.svgz',
    '*.pdf',
    '*.doc',
    '*.docx',
    '*.xls',
    '*.xlsx',
    '*.ppt',
    '*.pptx',
    '*.odt',
    '*.ods',
    '*.odp',
    '*.zip',
    '*.tar',
    '*.gz',
    '*.tgz',
    '*.bz2',
    '*.xz',
    '*.7z',
    '*.rar',
    '*.mp3',
    '*.wav',
    '*.flac',
    '*.ogg',
    '*.m4a',
    '*.mp4',
    '*.mkv',
    '*.mov',
    '*.avi',
    '*.webm',
    '*.ttf',
    '*.otf',
    '*.woff',
    '*.woff2',
    '*.eot',
  },
  formatters = {
    file = {
      truncate = vim.o.columns > 125 and 85 or 50,
    },
  },
  layouts = {
    default = {
      layout = {
        box = 'horizontal',
        width = 0.8,
        min_width = 120,
        height = 0.8,
        {
          box = 'vertical',
          border = 'single',
          title = '{title} {live} {flags}',
          { win = 'input', height = 1, border = 'bottom' },
          { win = 'list', border = 'none' },
        },
        {
          win = 'preview',
          title = '{preview}',
          border = 'single',
          width = 0.5,
        },
      },
    },
  },
  win = {
    input = {
      keys = {
        ['<C-v>'] = { 'edit_vsplit', mode = { 'i', 'n' } },
        ['<C-s>'] = { 'edit_split', mode = { 'i', 'n' } },
      },
    },
    list = {
      keys = {
        ['<C-v>'] = 'edit_vsplit',
        ['<C-s>'] = 'edit_split',
      },
    },
  },
}
