#!/usr/bin/env bash

# Stops further execution after any error.
set -e

readonly SETUP_DIR=$(dirname "$(realpath "$0")")

source "${SETUP_DIR}/helpers.sh"

getnf -u DroidSansMono,Hack && echo "$(check) Nerd fonts uninstalled"

[ -f "${DOTFILES_CONFIG_PATH}/dvim" ] && rm "${DOTFILES_CONFIG_PATH}/dvim" && echo "$(check) Removed dvim config"
[ -f ~/.local/bin/dvim ] && rm ~/.local/bin/dvim && echo "$(check) Removed dvim executable"

echo "$(check) dvim successfully uninstalled"
